POST http://localhost:8000/run
Content-Type: application/json

{
    "code": "console.log('Hello World');"
}

###

GET ls-capstone-team1-code-execution-server.8amvljcm2giii.us-west-2.cs.amazonlightsail.com

###

POST https://ls-capstone-team1-code-execution-server.8amvljcm2giii.us-west-2.cs.amazonlightsail.com/run
Content-Type: application/json

{
    "code": "console.log('Hello World');"
}

###

POST https://ls-capstone-team-1-gh-actions-code-execution-server.8amvljcm2giii.us-west-2.cs.amazonlightsail.com/run
Content-Type: application/json

{
    "code": "console.log('Goodbye World');"
}
